### ISSUE TITLE
Unable to login after 2/25/19

### ISSUE THREAD

**Issue by mreishus** [texasaggie97/hover-dns-updater#7]
My hover-dns-updater stopped being able to log into my account on 2/25. It gets a HoverException: <Response [401]> when posting to the signin page.  I haven't changed the password.  I'm debugging the username/password and it seems to be fine.  Still looking into it, wanted to know if @texasaggie97 or anyone else using this project can say if they see the same problem or no.

**Comment by mreishus** [comment]
Ok, I've done a fair bit of debugging and I don't know what the issue is.  I'm getting "Invalid username or password" back from hover, but I've verified the password and username it's trying are correct.  This issue is so weird, I want to chalk it up to me being dumb... please close unless someone else is able to see this issue as well.

**Comment by mreishus** [comment]
Ah! I changed the request url to `"https://www.hover.com/api/login"` after seeing [this gist](https://gist.github.com/dankrause/5585907) and it worked.

**Comment by NelsonMinar** [comment]
That fix worked for me too.

**Comment by CookedApps** [comment]
That worked like a charm. The pull request should be accepted.
